setOnActuator(actuator(brain(aI(x(X))))):-
setOnActuator(actuator(brain(aI(y(X))))):-
setOnActuator(actuator(brain(aI(turretTypeName(X))))):-
%enemies(sensors(sensorsDataListsManager(enemies(X,enemySensorData(health(V)))))).
%enemies(sensors(sensorsDataListsManager(enemies(X,enemySensorData(type(V)))))).
%enemies(sensors(sensorsDataListsManager(enemies(X,enemySensorData(x(V)))))).
%enemies(sensors(sensorsDataListsManager(enemies(X,enemySensorData(y(V)))))).
%nodes(sensors(sensorsDataListsManager(nodes(X,nodeSensorData(turretTypeName(V)))))).
%nodes(sensors(sensorsDataListsManager(nodes(X,nodeSensorData(x(V)))))).
%nodes(sensors(sensorsDataListsManager(nodes(X,nodeSensorData(y(V)))))).
%player(gameMaster(playerStats(money(X)))).
%player(gameMaster(playerStats(lives(X)))).
